### ISSUE TITLE
logo hk

### ISSUE THREAD

**Issue by ErdemHilmi** [mlevent/fatura#11]
Merhaba

firma logosu eklenebiliyor mu acaba

**Comment by mlevent** [comment]
Maalesef şu an için böyle bir özellik yok. getHtml metoduyla faturanın html çıktısını alıp, dompdf/mpdf kütüphanelerini kullanarak kendiniz ekleyebilirsiniz. Boş bir vaktimde pakete böyle bir özellik ekleyebilir miyim diye bakacağım.
