### ISSUE TITLE
E fatura icin soru

### ISSUE THREAD

**Issue by tholkashen** [mlevent/fatura#16]
Selamlar bu kutuphane icin ellerinize saglik demek istyorum ancak e fatura kesebiliyormuyuz bu kutuphane ile cunkuu entegratorlerden kontur aliniyor bu islem nasil oluyor. earsiv degil e fatura

**Comment by mlevent** [comment]
Merhabalar, paket e-arşiv ile çalışır; e-fatura mükellefiyseniz maalesef kullanamazsınız.

**Comment by ErdemHilmi** [comment]
Merhaba

ayrıca belirtmek istedim,
efatura kullanmak için yasal olarak entegratörle çalışmak gerekiyor, ya da kendiniz entegratörlük başvurusu yapıp entegratör olmanız gerekiyor. edönüşüm de efatura e-xxx süreçlerinde (gib portal earşiv hariç) yasal 10 yıl saklama zorunluluğunu karşılamanız gerekiyor. iso belgeleri ekleniyor vs.. vs..
