### ISSUE TITLE
Connection refused for URI

### ISSUE THREAD

**Issue by Looden** [mlevent/fatura#17]
![resim](https://user-images.githubusercontent.com/12395846/216603462-94de2a8b-8190-4a2d-839f-6aa0d3d96310.png)

Bu hatayı alıyorum, gerçek kullanıcıda.

**Comment by mlevent** [comment]
Gib kaybaklı anlık bir durum muhtemelen. Hala aynı hatayı alıyor musunuz?

**Comment by Looden** [comment]
Evet, bugun de devam ediyor hata. Test ortamında sorun yok.

**Comment by mlevent** [comment]
php versiyonu nedir? var_dump(curl_version()); ne çıktı veriyor?

**Comment by Looden** [comment]
> php versiyonu nedir? var_dump(curl_version()); ne çıktı veriyor?

php -v : 8.1

var_dump(curl_version());

array(16) {
  ["version_number"]=>
  int(479488)
  ["age"]=>
  int(9)
  ["features"]=>
  int(364890013)
  ["ssl_version_number"]=>
  int(0)
  ["version"]=>
  string(6) "7.81.0"
  ["host"]=>
  string(19) "x86_64-pc-linux-gnu"
  ["ssl_version"]=>
  string(13) "OpenSSL/3.0.2"
  ["libz_version"]=>
  string(6) "1.2.11"
  ["protocols"]=>
  array(25) {
    [0]=>
    string(4) "dict"
    [1]=>
    string(4) "file"
    [2]=>
    string(3) "ftp"
    [3]=>
    string(4) "ftps"
    [4]=>
    string(6) "gopher"
    [5]=>
    string(7) "gophers"
    [6]=>
    string(4) "http"
    [7]=>
    string(5) "https"
    [8]=>
    string(4) "imap"
    [9]=>
    string(5) "imaps"
    [10]=>
    string(4) "ldap"
    [11]=>
    string(5) "ldaps"
    [12]=>
    string(4) "mqtt"
    [13]=>
    string(4) "pop3"
    [14]=>
    string(5) "pop3s"
    [15]=>
    string(4) "rtmp"
    [16]=>
    string(4) "rtsp"
    [17]=>
    string(3) "scp"
    [18]=>
    string(4) "sftp"
    [19]=>
    string(3) "smb"
    [20]=>
    string(4) "smbs"
    [21]=>
    string(4) "smtp"
    [22]=>
    string(5) "smtps"
    [23]=>
    string(6) "telnet"
    [24]=>
    string(4) "tftp"
  }
  ["ares"]=>
  string(0) ""
  ["ares_num"]=>
  int(0)
  ["libidn"]=>
  string(5) "2.3.2"
  ["iconv_ver_num"]=>
  int(0)
  ["libssh_version"]=>
  string(25) "libssh/0.9.6/openssl/zlib"
  ["brotli_ver_num"]=>
  int(16777225)
  ["brotli_version"]=>
  string(5) "1.0.9"
}

**Comment by Looden** [comment]
Sorunu çözdüm.
Ubuntu 22.04'te, /etc/ssl/opensl.cnf dosyasının en alt satırına;
Options = UnsafeLegacyRenegotiation
satırını ekleyince düzeldi.
Çok teşekkür ederim zaman ayırdığınız için.
