### ISSUE TITLE
ondalık kısmı hk

### ISSUE THREAD

**Issue by ErdemHilmi** [mlevent/fatura#20]
Merhaba,

fatura kalemlerinde virgül sonrası 2 üzeri gereksinimlerde
amount_format()
bölümünde 2 ye yuvarladığı için problem oluyor 
invoiceitemmodal tarafında birim fiyatta amount_format ı kaldırınca düzeliyor
amount_format bu fonksiyonu da nereden aldığını bulduramadım dosyalar içinde

**Comment by mlevent** [comment]
Bu konuyla ilgili; model kullanımında tutarların tam olarak e-arşiv portal ile eşleşmeme durumu vardı. Sorun çözülmüştü ama tag release etmemiştim, az önce yeni bir versiyon yayınladım.

Burada şöyle ekstra bir durum var, e-arşiv portalda birim fiyat için virgülden sonra 10 haneye kadar işlem yapabiliyorsunuz. Ancak genel toplamlar hesaplanırken portal otomatik olarak bu değerleri yuvarlıyor. Yani genel toplamını 128,587 olması gereken bir faturanın genel toplamı, en düşük birim kuruş 1 olduğu için 128,59'a yuvarlanıyor. Konuyla alakalı e-fatura forumda resmi bir cevap mevcut; https://forum.efatura.gov.tr/view.php?id=94

- Tutarları kendim hesaplayıp göndermek istiyorum derseniz; https://github.com/mlevent/fatura/blob/master/examples/createInvoiceManually.php
- amount_format fonksiyonu için; https://github.com/mlevent/fatura/blob/master/src/Utils/Helpers.php

Kolay gelsin.

**Comment by ErdemHilmi** [comment]
Merhaba

teşekkürler
