### ISSUE TITLE
E-Fatura Listesi

### ISSUE THREAD

**Issue by Hasokeyk** [mlevent/fatura#34]
Merhabalar,

E-Arşive faturalarını alabiliyorum ama E-Faturaları nasıl alabilirim?

**Comment by ErdemHilmi** [comment]
Merhaba

E-Fatura ları alabilmek için bir entegratör üzerinden Efatura mükellefi olmalısınız.
Efatura mükellefi olduğunuzda entegratörünüzün sunduğu web servisde gelen efaturalar servisini kullanarak veriyi alabilirsiniz.

iyi çalışmalar
