### ISSUE TITLE
Mükellef Sorgulama

### ISSUE THREAD

**Issue by 1YalcinSahin1** [mlevent/fatura#37]
Merhaba,

Mükellef sorgulama metotunuzda:

Anonim  , Limited şirketlerde unvan alanı dolu geliyor.

Ama şahıs şirketi veya mükellef değilse bunu ayırt edebileceğimiz bir kısım bulunmuyor. Bunu nasıl ayırt edebiliriz ? 

Bir de token expire süresi nedir ?

**Comment by 1YalcinSahin1** [comment]
Ben sadece mükellef sorgulama yapmak istiyorum. Herhangi bir fatura kaydı şu an yapmayacağım. Sadece müşterilerime panel içerisinde bir bilgi sunmak istiyorum.

**Comment by OrhanOzyalcin** [comment]
Aynı mantık. Faturaya yazmışsın veya bilgi göstermişsin. 

if(!empty($gelenveri['adi'l) || !empty($gelenveri['unvan'l)) {
echo 'Bilgiler Doğrulandı';
} else { echo 'Mükellef Bulunamadı.'; }

**Comment by 1YalcinSahin1** [comment]
Şahıs şirketi sorguladım. Unvan alanı boş geliyor. Unvan alanı dolu gelmesi gerekiyordu. Web sitesinden sorguladığımda mükelleftir bilgisi geliyor. 

Eğer şahıs şirketinde unvan alanı dolu gelmesi gerekiyorsa şu an kod üzerinden bu veri yanlış gelmektedir.

**Comment by OrhanOzyalcin** [comment]
Kestiğin kişinin şirket veya mükellef olmaması ne fark eder ki Sen zaten sattın malı ona satmışsın faturayı ona keseceksin?

**Comment by 1YalcinSahin1** [comment]
Alışveriş yapan kullanıcı e-fatura mükellefi ise faturasını e-fatura kesmek zorundasınız. Anonim , limited ve şahıs şirketi ise buna göre fatura kesiyorsunuz.

Mükellef sorgulama metotunda da şahıs ile şahıs şirketine sahip kullanıcısını ayırt eden bir veri yok.

Tüm fatura entegratörlerinde bunu ayırt eden bir özellik mutlaka var. Sorgulama servislerinde bu destekleniyor. Bu pakette sadece verilerin eksik olduğunu söylüyorum.

**Comment by mlevent** [comment]
E-arşiv portal böyle bir veri sağlamıyor. Gerek de yok zaten. Farklı bir çözüm aramalısınız.
