### ISSUE TITLE
İmport Ederken Hata

### ISSUE THREAD

**Issue by ugurgunes95** [mlevent/fatura#5]
Merhabalar, genellikle nodejs ile geliştirme yapıyorum bu yüzden kullanamamış olabilirim fakat aşağıdaki gibi bir hata yapıyorum:
`Uncaught Error: Class "Mlevent\Fatura\Gib" not found in /home/ugur/Belgeler/fatura-php/index.php:5`

**Comment by mlevent** [comment]
Sınıfı dahil etmemiş olabilirsiniz; `use Mlevent\Fatura\Gib;` Yol göstermesi açısından, /examples klasörü altındaki örneklere bakabilirsiniz.

**Comment by ugurgunes95** [comment]
Dönüş sağladığınız için teşekkürler, fakat zaten dediğiniz gibi kullanıyordum. Sonrasında aşağıdaki satırı ekleyince sorun halloldu.
`require dirname(__DIR__) . '/fatura-php/vendor/autoload.php';`
