### ISSUE TITLE
Test Ortamında Fatura Oluşturma

### ISSUE THREAD

**Issue by muglali20** [mlevent/fatura#58]
Merhaba; Bu Başarılı projeniz için öncelikle çok teşekkürler.
Test Ortamında Fatura Oluşturma işlemı yapılabılıyor mu  ? Denedım ancak Sistem hata vermektedir.
`$gib = (new Gib)->setTestCredentials()->login();
$ft_gonder=$gib->createDraft($invoice);
print_r($ft_gonder);
`
Şeklinde Yaptım 
`Fatal error: Uncaught Mlevent\Fatura\Exceptions\ApiException: İstek başarısız oldu. in `
Şeklinde hata alıyorum

**Comment by mlevent** [comment]
catch blogunda getResponse() metoduyla donen cevabi kontrol eder misiniz.

**Comment by mlevent** [comment]
işlemleri try blogu icinde yapin. hata varsa catch icinde yakalanacaktir. asagidaki ornegi kullanip donen cevabi kontrol eder misiniz.

try {

    $gib = (new Gib)->setTestCredentials()->login(); 

    //$invoice = new InvoiceModel...

    $ft_gonder=$gib->createDraft($invoice); 
    print_r($ft_gonder);

} catch(FaturaException $e){
    
    dd($e->getResponse(), false);
}

**Comment by muglali20** [comment]
Tamam teşekkurler:;




$invoice->addItem(
    new InvoiceItemModel(
        malHizmet     : 'Çimento',  // ✴️ Zorunlu   @string
        miktar        : 3,          // ✴️ Zorunlu   @float
        birim         : Unit::Adet,   // ☑️ Opsiyonel @Unit @default=Unit::Adet
        birimFiyat    : 1259,       // ✴️ Zorunlu   @float
        kdvOrani      : 20,         // ✴️ Zorunlu   @float
        iskontoOrani  : 0.00,         // ✅ Opsiyonel @float
        iskontoTipi   : 'İskonto', // ☑️ Opsiyonel @string @default=İskonto
        iskontoNedeni : '',         // ✅ Opsiyonel @string
    ))->addTax(Tax::GVStopaj, 25);

Vergi Ekleme de

Fatal error: Uncaught Error: Call to undefined method Mlevent\Fatura\Models\InvoiceModel::addTax() in C:\xampp\htdocs\e-arsiv_v2\test.php:57 Stack trace: #0 {main} thrown in C:\xampp\htdocs\e-arsiv_v2\test.php on line 57

Bu şekilde hata oluyor neden olabılır
use Mlevent\Fatura\Enums\Currency;
use Mlevent\Fatura\Enums\InvoiceType;
use Mlevent\Fatura\Enums\Unit;
use Mlevent\Fatura\Gib;
use Mlevent\Fatura\Models\InvoiceModel;
use Mlevent\Fatura\Models\InvoiceItemModel;
use Mlevent\Fatura\Enums\Tax;
Şeklinde keleme yaptım vergi ekleme yapınca hat aoluyor onu silersen direk fatura oluşturuluyor

**Comment by mlevent** [comment]
examples klasörü içinde kullanım örnekleri mevcut. vergi ekleyecekseniz examples/createInvoiceWithExtras.php dosyasını inceleyebilirsiniz. hatta test için doğrudan bu dosyayı çalıştırın.

**Comment by mlevent** [comment]
Vergiyi belgeye eklediğiniz için bu hatayı alıyorsunuz. Verginin belgeye eklenen öğeye eklenmesi gerek. Dökümanı incelemek faydalı olacaktır.

**Comment by muglali20** [comment]
Evet Haklısınız Şimdı oldu peki 
/examples/createInvoice.php
Örneğinizde Bilgileri göndermek daha kolay ve anlaşılır bu örneğe göre fatura oluştmak istersek 
burada Ek vergi ve Ürünlerde birim cinsini nasıl ilave edebiliriz.
örnek verebılır mısınız
