### ISSUE TITLE
cURL error 35: OpenSSL/3.1.2

### ISSUE THREAD

**Issue by birkanozdamar** [mlevent/fatura#64]
Merhaba , bu proje için elinize emeğinize sağlık.
curl hiç bir şekilde atamıyorum. gerçek bir kullanıcıyla aşağıdaki gibi bir hata veriyor.
cURL error 35: OpenSSL/3.1.2: error:0A000152:SSL routines::unsafe legacy renegotiation disabled (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://earsivportal.efatura.gov.tr/earsiv-services/assos-login.
Test kullanıcısı ile token alabiliyorum.

Saygılarımla.

**Comment by birkanozdamar** [comment]
@mlevent  bu şekilde eklendi ama düzelmedi maalesef
[openssl.txt](https://github.com/mlevent/fatura/files/13254807/openssl.txt)

en üste eklendi:
openssl_conf = openssl_init
en alta eklendi:
[openssl_init]
ssl_conf = ssl_sect
[ssl_sect]
system_default = system_default_sect
[system_default_sect]
Options = UnsafeLegacyRenegotiation

**Comment by mlevent** [comment]
Dosyanın en altına eklemeyi denediniz mi?

**Comment by birkanozdamar** [comment]
openssl_conf = openssl_init
[openssl_init]
ssl_conf = ssl_sect
[ssl_sect]
system_default = system_default_sect
[system_default_sect]
Options = UnsafeLegacyRenegotiation

Bu blok hepsini /etc/ssl/openssl.cnf içine en alta eklediğimde oldu.
Teşekkürler @mlevent
