### ISSUE TITLE
paket hakkinda

### ISSUE THREAD

**Issue by furkansoydas** [mlevent/fatura#65]
butun talimatlara uyarak giris yapmayi denedim ancak herhangi bir sonuca ulasamadim onun yerine gib e imza sayfasini cikardi karsima. bu paketi en son ne zaman kullandiniz? paket hala calisiyor mu?

**Comment by mlevent** [comment]
Paket güncel ve çalışıyor. Herhangi bir hata almıyor musunuz?

**Comment by ahmeti** [comment]
2023 Ağustos sonunda büyük miktarda yurt dışı IP adreslerini blokladılar. AWS, Digital Ocean kullanıyorsanız bu nedenle erişemeyebilirsiniz. Bilginiz olsun.
