### ISSUE TITLE
GetDownloadURL ve SMSVerification Problemleri

### ISSUE THREAD

**Issue by adaman001** [mlevent/fatura#67]
Merhaba. Oncelikle kodlariniz muhtesem sekilde calismakta bu kutuphane icin cok tesekkur ederim. Fatura olusturma duzenleme silme vs islemleri gayet guzel calismakta yalniz indirme linki ile dosyayi indirmeye calistigimizda her zaman oturum zaman asimina ugradi hatasi dondurmekte. Logout yaptirmadan indirme linkini alip dosyayi indirmeye calistigimizda da yine hata donduruyor. Ayrica smsverification islemlerini baslatmaya calistigimiz zaman sunucu 500 hatasi veriyor. Ama en onemli sorunumuz su an fatura indirme linkinin calismamasi :(

**Comment by mlevent** [comment]
Merhabalar,

indirme linkini token'ı oluşturduğunuz ip dışında kullanamazsınız. Token'ı sunucuda oluşturuyorsanız, indirme linkine de yalnızca sunucunuzda erişebilirsiniz. Burada yapacağınız şey, indirme linkini kullanarak dosyayı sunucuya kaydetmek ve kendi sunucunuz üzerinden indirme işlemi yapmak. Bunun için [saveToDisk](https://github.com/mlevent/fatura/blob/master/src/Gib.php#L427) metodonu kullanabilir ya da kendiniz basit bir kod ile dosyayı kendi sunucunuza ya da farklı bir yere kaydedebilirsiniz.

Sms doğrulama işlemlerini test hesapları üzerinden gerçekleştiremezsiniz. Yetki hatası dönecektir.

İyi çalışmalar, kolaylıklar dilerim.

**Comment by adaman001** [comment]
tekrardan merhaba
evet şimdi sunucuya indirme işlemini sagladım çalışıyor. çok teşekkür
ederim. saveToDisk fonksiyonunuzu kullandım ama .zip olarak kaydediyor
sunucuya bunu .pdf olarak kaydetmek için ne yapabiliriz

Mert Levent ***@***.***>, 3 Ara 2023 Paz, 17:00 tarihinde
şunu yazdı:
