### ISSUE TITLE
Varsayılan Notların İptal Edilmesi Hk.

### ISSUE THREAD

**Issue by ahmeti** [mlevent/fatura#68]
Merhaba,
Varsayılan notlar kaldırıldıktan sonra yeni bir release oluşturulmamış ve `composer install` ile [v0.2.3](https://github.com/mlevent/fatura/releases/tag/v0.2.3) setNote olan versiyonu yükleniyor. Dolayısıyla varsayılan notlar, __constuct metodundaki not alanını ezerek üzerine yazıyor.

Mümkünse yeni bir release oluşturabilir misiniz?
Teşekkür ederim, ellerinize sağlık.

https://github.com/mlevent/fatura/commit/115d77c6a91a38165a396007c79d1deef2a8b33b

https://github.com/mlevent/fatura/blob/5959f5af81b31b13a00d44fa35a2fdc570c17dc2/src/Models/AbstractModel.php#L149-L153

**Comment by mlevent** [comment]
Merhabalar. 
Uyarı için teşekkür ederim. Yeni versiyonu yayınladım diye hatırlıyordum ama unutmuşum. Tekrar teşekkür ederim.
[v0.2.4](https://github.com/mlevent/fatura/releases/tag/v0.2.4)

**Comment by ahmeti** [comment]
Sağ olun, çok teşekkürler.
