### ISSUE TITLE
belge işlemleri

### ISSUE THREAD

**Issue by hiberblsm** [mlevent/fatura#69]
belge işlemlerinde $gib->getHtml('1d78ef40-6491-11ed-a280-4ccc6ae28384');
ve earşiv icerigini goruntuleme saglanamıyor bunla ilgilenme şansınız varmı acaba

**Comment by mlevent** [comment]
Merhabalar, herhangi bir hata almıyor musunuz?

**Comment by hiberblsm** [comment]
> Merhabalar, herhangi bir hata almıyor musunuz?

<b>Mlevent\Fatura\Exceptions\ApiException</b>
: İstek başarısız oldu. in <b>/vendor/mlevent/fatura/src/Client.php</b>
on line <b>50</b>     hata tam olarak bu sanırım kutuphanede bir gunceleme gerkeli php 8,3 versiyon kulanıyorum

**Comment by mlevent** [comment]
Tekrar merhabalar,

`getHtml` metoduna gönderdiğiniz ettn şu ise; `1d78ef40-6491-11ed-a280-4ccc6ae28384` sonuç alamamanız normal. böyle bir belge yok. bu, dökümanda bulunan örnek bir kullanım. 

kendi oluşturduğunuz bir belgeye ait ettn bilgisiyle tekrar deneyin.

İyi günler, kolaylıklar dilerim.

**Comment by hiberblsm** [comment]
aşagıdaki hata geliyorArray(    [token] => 2117857b35ff8b5d9b9eb561951193fa0f8b4c91e327bb2bdec6a8d2b2258945f9e8a5d40442260e5c4e537047a68aca53cea161ab5b107294502ad6e3969bd5    [redirectUrl] => index.jsp)Array(    [error] => 1    [messages] => Array        (            [0] => String index out of range: 4        )     [metadata] => Array        (            [optime] => 20240307002851+0300        ) )<b>Mlevent\Fatura\Exceptions\ApiException</b>: İstek başarısız oldu. in <b>/www/wwwroot/hiber.com.tr/storage/vendor/mlevent/fatura/src/Client.php</b> on line <b>51</b> 07.03.2024, 00:25, "Mert Levent" ***@***.***>: try {

    ...

    echo $gib->getHtml('');

} catch(FaturaException $e){
    
    var_dump($e->getResponse());
}getResponse ne cevap dönüyor?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mlevent** [comment]
`getHtml` metodu gelen faturalar için kullanılamıyor.
