### ISSUE TITLE
İskonto Sütunları

### ISSUE THREAD

**Issue by eneskomur** [mlevent/fatura#70]
Fatura kalemlerinin hiçbiri için iskontoya dair bir tanımlama yapmasam da fatura kalemlerinde ve genel toplam alanında iskonto bilgileri oluşturuluyor.

![iskonto](https://github.com/mlevent/fatura/assets/5255758/0f82c7e8-f2d5-4278-a196-13da0aef014c)

![iskonto-data](https://github.com/mlevent/fatura/assets/5255758/aa91fbb0-0f15-4fea-a7a2-54eff7565866)

**Comment by mlevent** [comment]
Merhabalar,

İskonto satırı GIB Portal tarafında otomatik oluşturuluyor. Portal üzerinden elle fatura kesmeyi denediğinizde de aynı sonucu göreceksiniz. Doğrusu da bu. Faturada iskonto olmadığını gösteriyor.

İyi günler, kolaylıklar dilerim.
