### ISSUE TITLE
Composer kurulum esnasında hata

### ISSUE THREAD

**Issue by eneskara16** [mlevent/fatura#76]
Merhaba,

Composer kurulum esnasında hata alıyorum

Problem 1
    - Root composer.json requires ilevent/fatura ^4.2.1 -> satisfiable by ilevent/fatura[4.2.1].
    - ilevent/fatura[4.2.1] requires guzzlehttp/guzzle ^7.5 -> found guzzlehttp/guzzle[7.5.0, ..., 7.9.2] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require ilevent/fatura:^4.2" to figure out if any version is installable, or "composer require ilevent/fatura:^4.2 --with-all-dependencies" to update all dependencies to be compatible with the new version constraint.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by OrhanOzyalcin** [comment]
Merhaba

`composer require guzzlehttp/guzzle`

Projenize dahil edip tekrar denermisiniz
