### ISSUE TITLE
belge indirme hatası

### ISSUE THREAD

**Issue by Rolanss** [mlevent/fatura#79]
Merhaba e-faturayı belge olarak indirme adresine tıkladığım da sürekli şu hatayı alıyorum : 
{"error":"1","messages":[{"type":"4","text":"Oturum geçersiz, token yok"}]}

bu sorunu yaşayan veya çözen var mı?

**Comment by OrhanOzyalcin** [comment]
Merhaba Login işleminden gelen token kontrolü yaptınız mı?

**Comment by mlevent** [comment]
Merhabalar,

indirme linkini token'ı oluşturduğunuz ip dışında kullanamazsınız. Token'ı sunucuda oluşturuyorsanız, indirme linkine de yalnızca sunucunuzda erişebilirsiniz. Burada yapacağınız şey, indirme linkini kullanarak dosyayı sunucuya kaydetmek ve kendi sunucunuz üzerinden indirme işlemi yapmak. Bunun için [saveToDisk](https://github.com/mlevent/fatura/blob/master/src/Gib.php#L427) metodonu kullanabilir ya da kendiniz basit bir kod ile dosyayı kendi sunucunuza ya da farklı bir yere kaydedebilirsiniz.

İyi çalışmalar, kolaylıklar dilerim.
