### ISSUE TITLE
İstek başarısız oldu

### ISSUE THREAD

**Issue by pseudonymousUser** [mlevent/fatura#83]
Önceden oluşturduğum dökümanın ETTN'si ile işlem yapınca "İstek başarısız oldu" yanıtı dönüyor. Örneğin;

Başarılı bir şekilde fatura taslağı oluşuturup dönen ETTN'yi kayıt ediyorum.
$invoice->getUuid(); // 04e17398-468d-11ed-b3cb-4ccc6ae28384

Faturayı oluşturduğum $gib nesnesiyle çalışıyor örneğin şu çalışıyor;
$gib->getHtml($invoice->getUuid());

Fakat daha sonra login olup ETTN'yi daha sonra bu şekilde kullanmak istediğimde; 

$gib = (new Gib())->setTestCredentials(333333, 666666)->login();
$gib->getHtml('04e17398-468d-11ed-b3cb-4ccc6ae28384');

Burada getHtml 'İstek başarısız oldu' yanıtı dönüyor. getDocument fonksiyonu da aynı hatayı veriyor.

getHtml'in herhangi bir zamanda daha önceden kayıt edilmiş taslağı getirebilmesi gerekmiyor mu?

// Client.php $parameters;
array(5) {
  ["callid"]=>
  string(36) "04e17398-468d-11ed-b3cb-4ccc6ae28384"
  ["token"]=>
  string(128) "817c54d6183c42bc8b6eb6a2d93bc61e30f28553660c7c747c8bb08a3bab86e884d0370fe2362c33ea3360801ee88549f91fa78faeaf0c56d9f219fb1b825066"
  ["cmd"]=>
  string(27) "EARSIV_PORTAL_FATURA_GOSTER"
  ["pageName"]=>
  string(12) "RG_TASLAKLAR"
  ["jp"]=>
  string(77) "{"ettn":"04e17398-468d-11ed-b3cb-4ccc6ae28384","onayDurumu":"Onayland\u0131"}"
}

// Client.php $this->response;
array(3) {
  ["error"]=>
  string(1) "1"
  ["messages"]=>
  array(1) {
    [0]=>
    string(28) "String index out of range: 4"
  }
  ["metadata"]=>
  array(1) {
    ["optime"]=>
    string(19) "20240916112936+0300"
  }
}

// Client.php $request->getStatusCode()
int(200)

**Comment by mlevent** [comment]
Merhabalar, 

faturayı farklı bir test hesabında oluşturuyor olabilir misiniz?

**Comment by pseudonymousUser** [comment]
Merhabalar, 

Hayır, $key = 333333, $password = 666666 bu değerler sabit. Farklı bir test hesabıyla da denedim sonuç aynı oldu. getDownloadURL methodu çalışıyor URL dönüyor. getHTML ve getDocument hata veriyor.

**Comment by mlevent** [comment]
bu test hesabını nasıl kullanıyorsunuz? aynı bilgilerle giriş yapmayı dener misiniz; https://earsivportaltest.efatura.gov.tr/login.jsp

**Comment by pseudonymousUser** [comment]
Haklısınız bu bilgilerle test hesabı girişi yapılamıyor. Fakat başarılı bir şekilde fatura oluşturup geri döndüğü için giriş bilgilerinin çalışıyor olduğunu varsaymıştım. Benim fonksiyonum içerisindeki hatalı bir foreach'den dolayı $key ve $password null olarak tanımlanıyormuş. Bu sebeple her defasında farklı kullanıcıyla oturum açıyormuş. Düzeltince çalışıyor herhangi bir problem yok. Hatanın kaynağı bendeymiş, zamanınızı aldım, üzgünüm. Teşekkür ederim.

**Comment by mlevent** [comment]
Rica ederim. Sorunun çözüldüğüne sevindim. Kolaylıklar dilerim.
